[package]
name = "mvp-staking-pool"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-pausable = { version = "0.1.0", path = "../soroban_pausable" }
soroban_reentrancy_guard = { version = "0.1.0", path = "../soroban_reentrancy_guard" }
soroban_pausable_core = { path = "../soroban_pausable_core" }
soroban-sdk = "22.0.7"
soroban_access_control_core = { path = "../soroban_access_control_core" }
soroban_storage_ttl = { path = "../soroban_storage_ttl" }
soroban_upgrade_governance_core = { path = "../soroban_upgrade_governance_core" }

[dev-dependencies]
soroban_storage_ttl = { path = "../soroban_storage_ttl", features = ["testutils"] }
soroban-sdk = { version = "22.0.7", features = ["testutils"] }
